### PR TITLE
add toolbar.scss (WIP)

### PR DESCRIPTION
**Pull request by ebrehault**
I have tried to migrate toobar styles to SCSS as it was missing after Ramaon changes.
But it looks crappy right now.
@bloodbare any hints ?

### CODE REVIEW

**Comment by bloodbare** [comment]
there is a main app scss file at src/components/app/app.component.scss that is the file that loads on application. All the other scss files should be loaded on the component itself (I'm not using the barcelona.plone.scss because it does not make any sense to load all in one place)

So I would move the toolbar.scss to toolbar component folder and require on the component itself.

**Comment by ebrehault** [comment]
Ok, so we just load variables.scss from every component-specific scss, and it should be ok.
Fine, let me try that.

**Comment by jensens** [comment]
Hence there was no activity for a long time, I propose to close this PR within next two weeks. If you do not feel ok with this, please speak up and provide us a rough schedule.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
